config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
 
  resources :items do
    member do
      patch :complete
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.all.order("created_at DESC")
  end
  
  def new
    @items = Item.new
  end
  def create
      @items = Item.new(item_params)
      if @items.save
         redirect_to root_path
      else
        render 'new'
      end
  end
  
  def show
      @item = Item.find(params[:id])
  end
  
  def edit
      @item = Item.find(params[:id])
  end
  
  def abbort
      @item = Item.find(params[:id])
      redirect_to item_path(@item)
  end
  
  def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
          redirect_to item_path(@item)
      else
          render 'edit'
      end
  end
  
  def complete
      @item = Item.find(params[:id])
      @item.update_attribute(:completed_at, Time.now)
      redirect_to root_path
  end
  
  def destroy
      @item = Item.find(params[:id])
      @item.destroy
      redirect_to root_path
  end
  
  private
  
  def item_params
      params.require(:item).permit(:title, :description)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1> Aufgabe editieren</h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Aufgabe" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit, "Editieren" %>
<%= link_to "Abbrechen", item_path, :class => "btn btn-default" %>
<% end %>

app/views/items/index.html.erb
<h1>Meine Aufgaben</h1>
<p>Neue Aufgaben eintragen...</p>

<%= link_to "Neue Aufgabe", new_item_path, :class => "btn btn-default" %>
<hr>
<% @items.each do |item| %>
  <div class="row item">
    <% if item.completed? %>
      <div class="col-md-6">
      <h2><s><%= link_to item.title, item %></s></h2>
      <p>
        <%= time_ago_in_words(item.completed_at)%> ago.
        </p>
      </div>
      <div class="col-md-2">
      </div>
    <% else %>
          <div class="col-md-6">
      <h2><%= link_to item.title, item %></h2>
      <p><%= item.description %></p>
      </div>
      <div class="col-md-2">
       <%= link_to complete_item_path(item), method: :patch do %>
       <h3><i class="fas fa-check-circle"></i></h3>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/new.html.erb
<h1> Neue Aufgabe anlegen</h1>

<%= simple_form_for @items do |f| %>
  <%= f.input :title, label: "Aufgabe" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit, "Erstellen" %>
<% end %>

app/views/items/show.html.erb
<h2><%= @item.title %></h2>
<p><%= @item.description %></p>

<%= link_to root_path do %>
  <i class="fas fa-chevron-circle-left"></i>
<% end %>
<%= link_to edit_item_path do %>
  <i class="far fa-edit"></i>
<% end %>
<%= link_to item_path(@item), method: :delete, data: { confim: "Bist du sicher?" } do %>
  <i class="far fa-trash-alt"></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
<div class="container">
<%= yield %>
  </div>

</body>
</html>